zadanie1.exe: zadanie1.obj
	link /DEBUG /OUT:zadanie1.exe zadanie1.obj
	link /DEBUG /OUT:zadanie2.exe zadanie2.obj
	link /DEBUG /OUT:zadanie3.exe zadanie3.obj
	link /DEBUG /OUT:zadanie4.exe zadanie4.obj


zadanie1.obj: zadanie1.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie1.obj zadanie1.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie2.obj zadanie2.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie3.obj zadanie3.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie4.obj zadanie4.cpp