zadanie5.exe: zadanie5.obj
	link /DEBUG /OUT:zadanie5.exe zadanie5.obj
	link /DEBUG /OUT:zadanie6.exe zadanie6.obj


zadanie5.obj: zadanie5.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie5.obj zadanie5.cpp
	cl /std:c++17 /EHsc /c /Zi /W4 /WX /Zi /Fo:zadanie6.obj zadanie6.cpp

